### ISSUE TITLE
The CONTRIBUTING.md has broken link to CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by KonstantinGetready** [merokudao/dApp-sdk#7]
Hello,

when I click on the "By participating in this project, you agree to abide by our [Code of Conduct](https://github.com/merokudao/dApp-sdk/blob/main/CODE_OF_CONDUCT.md)." in the CONTRIBUTING.md I see 404 error.

**Comment by r4881t** [comment]
This has been fixed by https://github.com/merokudao/dApp-sdk/commit/63fe031125ec9782eaab147ca03c6cdec352eba9
